### ISSUE TITLE
Update to Dart 2.1

### ISSUE THREAD

**Issue by Solido** [FooStudio/tinycolor#1]
Flutter & Pigment have updated their dependencies.
Thanks !

**Comment by mendieta** [comment]
@Solido the library is already compatible with Dart 2.1

`sdk: ">=2.0.0-dev.48.0 <3.0.0"
`

**Comment by Solido** [comment]
Ah still have some error on my update ! maybe some cache since pigment updated flutter dependencies but not version number

For the record
`Because every version of tinycolor depends on pigment >=0.1.1 <1.0.3 which requires SDK version >=1.2.0 <=2.0.0, tinycolor is forbidden.
So, because flutter_calender depends on tinycolor ^1.0.1, version solving failed.`

**Comment by Solido** [comment]
I reopen pigment: ^1.0.3 is the last version and tinycolor depends on 
`dependencies:
  pigment: ^0.1.3`

^1.0.3 =! ^0.1.3

Can it be the cause ?

**Comment by mendieta** [comment]
@Solido you are totally right the version of pigment used was old, i've uploaded a new version to pub with the correct dependencies. That should fix the error.
